# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and push docker iamge to registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://koyina.azurecr.io/
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{vars.REGISTRY_HOST}}/${{ secrets.REGISTRY_USERNAME }}/${{vars.IMAGE_NAME}}:${{ github.sha }}
        file: ${{vars.DOCKERFILE_PATH}}